language: go

install:
  - go get github.com/gohugoio/hugo
script:
  - hugo
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
